### ISSUE TITLE
clang 9 build error

### ISSUE THREAD

**Issue by orbea** [levaidaniel/ksh-openbsd#2]
On Slackware current with `clang-9.0.0` `ksh-openbsd-20190804` fails to build.
```
clang -fPIC -Wall -Wpointer-arith -Wuninitialized -Wstrict-prototypes -Wmissing-prototypes -Wunused -Wsign-compare -Wshadow -Wdeclaration-after-statement `getconf LFS_CFLAGS` -DEMACS -DVI   -c -o vis.o vis.c
vis.c:142:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
DEF_WEAK(vis);
^
vis.c:142:10: error: a parameter list without types is only allowed in a function definition
DEF_WEAK(vis);
         ^
vis.c:168:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
DEF_WEAK(strvis);
^
vis.c:168:10: error: a parameter list without types is only allowed in a function definition
DEF_WEAK(strvis);
         ^
2 warnings and 2 errors generated.
make: *** [<builtin>: vis.o] Error 1
```
Removing the two `DEF_WEAK` instances in `vis.c` allows the build to succeed, I'm not sure they are needed?

**Comment by levaidaniel** [comment]
I think you're absolutely right, we don't need those macros there. That file (vis.c) was a hard copy from OpenBSD's libc tree, and a couple of functions are being used from there in history.c. But not even those that are being treated with DEF_WEAK().
I'll remove it in a next commit.

Thanks for noticing!
